- name: create package directory
  file:
    path: "{{ rock_cache_dir }}/Packages"
    state: "directory"

- name: download packages
  repobuilder:
    packages: "{{ download_packages }}"
    groups: "{{ package_groups }}"
    config: "{{ role_path }}/files/rock-offline.repo"
    download_path: "{{ rock_cache_dir }}/Packages"
    exclude: "i686"
    tempcache: true

- name: gather list of rpms to Sign
  find:
    paths:
      - "{{ rock_cache_dir }}/Packages"
    patterns: "*.rpm"
    file_type: "file"
  register: find_result

- name: Signing packages
  rpmsign:
    rpms: "{{ find_result.files | map(attribute='path') | list }}"
    passphrase: "{{ gpg_passphrase }}"
    key: "{{  gpg_key_name }}"
    macros:
      _gpg_check_password_cmd: "/bin/true"
  become: yes
  become_user: user
  no_log: true
  when: not skip_gpg

- name: clear old repo data
  file:
    state: absent
    path: "{{ rock_cache_dir }}/repodata"


- name: generate fresh repo data
  command: createrepo_c "{{ rock_cache_dir | quote }}"

- name: create support directory
  file:
    path: "{{ rock_cache_dir }}/support"
    state: "directory"

- name: download ET snort rules
  get_url:
    url: https://rules.emergingthreats.net/open/snort-2.9.0/emerging.rules.tar.gz
    dest: "{{ rock_cache_dir }}/support/emerging.rules-snort.tar.gz"
    mode: 0644

- name: download ET Suricata rules
  get_url:
    url: https://rules.emergingthreats.net/open/suricata/emerging.rules.tar.gz
    dest: "{{ rock_cache_dir }}/support/emerging.rules-suricata.tar.gz"
    mode: 0644

- name: download pulled pork
  get_url:
    url: https://github.com/shirkdog/pulledpork/archive/{{ pulledpork_release }}.tar.gz
    dest: "{{ rock_cache_dir }}/support/pulledpork-{{ pulledpork_release }}.tar.gz"
    mode: 0644

- name: download RockNSM scripts
  get_url:
    url: https://github.com/rocknsm/rock-scripts/archive/{{ rockscripts_branch }}.tar.gz
    dest: "{{ rock_cache_dir }}/support/rock-scripts_{{ rockscripts_branch }}.tar.gz"
    mode: 0644

- name: download RockNSM dashboards
  get_url:
    url: https://github.com/rocknsm/rock-dashboards/archive/{{ rockdashboards_branch }}.tar.gz
    dest: "{{ rock_cache_dir }}/support/rock-dashboards_{{ rockdashboards_branch }}.tar.gz"
    mode: 0644

- name: sign all the things
  command: gpg2 --detach-sign --yes --armor -u security@rocknsm.io {{ item | quote }}
  with_items:
    - "{{ rock_cache_dir }}/repodata/repomd.xml"
    - "{{ rock_cache_dir }}/support/emerging.rules-snort.tar.gz"
    - "{{ rock_cache_dir }}/support/emerging.rules-suricata.tar.gz"
    - "{{ rock_cache_dir }}/support/pulledpork-{{ pulledpork_release }}.tar.gz"
    - "{{ rock_cache_dir }}/support/rock-scripts_{{ rockscripts_branch }}.tar.gz"
    - "{{ rock_cache_dir }}/support/rock-dashboards_{{ rockdashboards_branch }}.tar.gz"
  when: not skip_gpg
